version: "2"
services:

  database:
    image: mysql
    hostname: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:5000
    depends_on:
      - database
    links:
      - database:db
